#!/Library/Frameworks/Python.framework/Versions/3.7/bin/python3
import pyperclip as p
prev_clip = open("/Users/scottmolloy/Desktop/.alfredWork/functions/previous_clip.txt", "r")
content = prev_clip.read()

def latex(example):
    example = example.split(" ")
    i = 0
    while(i<len(example)):
        if "/" in example[i]:
            rbrack = "}"
            lbrack = "{"
            example[i] = example[i].split("/")
            example[i] = f"\\frac{lbrack}{example[i][0]}{rbrack}{lbrack}{example[i][1]}{rbrack}"
            i+=1
    example = " ".join(example)
    return(example.replace("(","\\left(").replace(")","\\right)"))

p.copy(latex(content))	