#!/anaconda3/bin/python3
file = open("name_of_file.txt", "r")
seq = file.read()
file.close()
seq = seq.replace(" _", "_")
print(seq)
file = open(seq, "r")
content = file.read()
file.close()
file = open(f"operate/{seq}", "w")
file.write(content)
file.close()
file = open(f"operate/ripcord.txt", "w")
file.write("valid")
file.close()