#!/Library/Frameworks/Python.framework/Versions/3.7/bin/python3
from pynput.keyboard import Key, Controller
keyboard = Controller()
import time
keyboard.press(Key.tab)
keyboard.release(Key.tab)
time.sleep(.3)
keyboard.press(Key.tab)
keyboard.release(Key.tab)
time.sleep(.3)
keyboard.press(Key.tab)
keyboard.release(Key.tab)
time.sleep(.3)
keyboard.press(Key.tab)
keyboard.release(Key.tab)
time.sleep(.3)
with keyboard.pressed(Key.shift):
    keyboard.press("a")
    keyboard.release("a")
time.sleep(.3)
keyboard.press(Key.space)
keyboard.release(Key.space)
time.sleep(.3)
with keyboard.pressed(Key.shift):
    keyboard.press("b")
    keyboard.release("b")
time.sleep(.3)
keyboard.press(Key.tab)
keyboard.release(Key.tab)
time.sleep(.3)
keyboard.type("sassafras")
