#!/usr/bin/python
_ls = open("ls.txt")
ls = _ls.read()
_ls.close()
ls = ls.replace(".txt", "")
ls = ls.replace("\n", "\t")
ls = ls.replace("retrieveVariable.py\t", "")
ls = ls.replace("listVariables.py\t", "")
ls = ls.replace("createVariable.py\t", "")
ls = ls.replace("createVariable.ssh\t", "")
ls = ls.replace("retrieveVariable.ssh\t", "")
ls = ls.replace("currentVariables.txt\t", "")
ls = ls.replace("currentVariables", "")
ls = ls.replace("rm\t", "")
ls = ls.replace("rm.py\t", "")
ls = ls.replace("rm.ssh\t", "")
ls = ls.replace("rmout.ssh\t", "")
ls = ls.replace("rmout.ssh\t", "")
ls = ls.replace("ls\t", "")
ls = ls.replace("\t\t", "\t")
ls = ls.replace("\t\t", "\t")
ls = ls.replace("\t\t", "\t")
out = open("currentVariables.txt", "w")
out.write(ls)
out.close()
